import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import Footer from "../components/Footer/Footer";
import Header from '../components/Header/Header';

// const myFont = localFont({ src: '../NeueHaasDisplayMediu.ttf' })
const inter = Inter({ subsets: ["latin"], variable: "--font-neue" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={`${inter.variable} font-sans`}>
        <div className="relative flex min-h-screen flex-col">
          {/* <SiteHeader /> */}
          <Header />
          <div className="flex-1">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
